# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestBug1links():
  def setup_method(self, method):
    self.driver = webdriver.Chrome(executable_path='C:\Driver\chromedriver.exe')
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_bug1links(self):
    self.driver.get("http://127.0.0.1:8000/login/")
    self.driver.set_window_size(1552, 880)
    self.driver.find_element(By.ID, "id_username").send_keys("Brayan@gmail.com")
    self.driver.find_element(By.ID, "id_password").send_keys("Br@yan123")
    self.driver.find_element(By.ID, "id_password").send_keys(Keys.ENTER)
    self.driver.find_element(By.LINK_TEXT, "Gallery").click()
    self.driver.find_element(By.LINK_TEXT, "Our Services").click()
    self.driver.find_element(By.LINK_TEXT, "About Us").click()
    self.driver.find_element(By.LINK_TEXT, "Jobs").click()
    self.driver.find_element(By.LINK_TEXT, "More").click()
    self.driver.find_element(By.CSS_SELECTOR, ".hero-body").click()
    self.driver.find_element(By.LINK_TEXT, "Log in").click()
    self.driver.find_element(By.CSS_SELECTOR, ".is").click()
    self.driver.find_element(By.LINK_TEXT, "Gallery").click()
    self.driver.find_element(By.CSS_SELECTOR, ".button > strong").click()
    self.driver.find_element(By.LINK_TEXT, "Apple Nail Salon & Spa").click()
  
