# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestTrytocreateappointmenttopart4notcomplete():
  def setup_method(self, method):
    self.driver = webdriver.Chrome(executable_path='C:\Driver\chromedriver.exe')
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_trytocreateappointmenttopart4notcomplete(self):
    # Test name: Try to create appointment (to part 4, not complete)
    # Step # | name | target | value
    # 1 | open | http://127.0.0.1:8000/login/ | 
    self.driver.get("http://127.0.0.1:8000/login/")
    # 2 | setWindowSize | 1552x880 | 
    self.driver.set_window_size(1552, 880)
    # 3 | type | id=id_username | Brayan@gmail.com
    self.driver.find_element(By.ID, "id_username").send_keys("Brayan@gmail.com")
    # 4 | type | id=id_password | Lemu$123
    self.driver.find_element(By.ID, "id_password").send_keys("Lemu$123")
    # 5 | sendKeys | id=id_password | ${KEY_ENTER}
    self.driver.find_element(By.ID, "id_password").send_keys(Keys.ENTER)
    # 6 | click | linkText=Book Appointment | 
    self.driver.find_element(By.LINK_TEXT, "Book Appointment").click()
    # 7 | click | css=.card:nth-child(2) .button | 
    self.driver.find_element(By.CSS_SELECTOR, ".card:nth-child(2) .button").click()
    # 8 | click | css=.card:nth-child(11) .button | 
    self.driver.find_element(By.CSS_SELECTOR, ".card:nth-child(11) .button").click()
    # 9 | click | linkText=Continue | 
    self.driver.find_element(By.LINK_TEXT, "Continue").click()
    # 10 | click | id=id_quantity | 
    self.driver.find_element(By.ID, "id_quantity").click()
    # 11 | select | id=id_quantity | label=10
    dropdown = self.driver.find_element(By.ID, "id_quantity")
    dropdown.find_element(By.XPATH, "//option[. = '10']").click()
    # 12 | click | css=tr:nth-child(1) form > .button | 
    self.driver.find_element(By.CSS_SELECTOR, "tr:nth-child(1) form > .button").click()
    # 13 | click | id=id_quantity | 
    self.driver.find_element(By.ID, "id_quantity").click()
    # 14 | select | id=id_quantity | label=9
    dropdown = self.driver.find_element(By.ID, "id_quantity")
    dropdown.find_element(By.XPATH, "//option[. = '9']").click()
    # 15 | click | css=tr:nth-child(1) form > .button | 
    self.driver.find_element(By.CSS_SELECTOR, "tr:nth-child(1) form > .button").click()
    # 16 | click | linkText=Continue | 
    self.driver.find_element(By.LINK_TEXT, "Continue").click()
    # 17 | click | name=technician | 
    self.driver.find_element(By.NAME, "technician").click()
    # 18 | click | css=.button:nth-child(1) | 
    self.driver.find_element(By.CSS_SELECTOR, ".button:nth-child(1)").click()
    # 19 | close |  | 
    self.driver.close()
  
