# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestChangePassword():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_changePassword(self):
    # Test name: Change Password
    # Step # | name | target | value
    # 1 | open | http://127.0.0.1:8000/customerView/ | 
    self.driver.get("http://127.0.0.1:8000/customerView/")
    # 2 | setWindowSize | 1552x880 | 
    self.driver.set_window_size(1552, 880)
    # 3 | mouseOver | linkText=My Account | 
    element = self.driver.find_element(By.LINK_TEXT, "My Account")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    # 4 | click | linkText=My Profile | 
    self.driver.find_element(By.LINK_TEXT, "My Profile").click()
    # 5 | click | linkText=Change Password | 
    self.driver.find_element(By.LINK_TEXT, "Change Password").click()
    # 6 | click | id=id_old_password | 
    self.driver.find_element(By.ID, "id_old_password").click()
    # 7 | type | id=id_old_password | Br@yan123
    self.driver.find_element(By.ID, "id_old_password").send_keys("Br@yan123")
    # 8 | type | id=id_new_password1 | Lemu$123
    self.driver.find_element(By.ID, "id_new_password1").send_keys("Lemu$123")
    # 9 | type | id=id_new_password2 | Lemu$123
    self.driver.find_element(By.ID, "id_new_password2").send_keys("Lemu$123")
    # 10 | click | xpath=//button[contains(.,'Change Password')] | 
    self.driver.find_element(By.XPATH, "//button[contains(.,\'Change Password\')]").click()
    # 11 | open | http://127.0.0.1:8000/login/ | 
    self.driver.get("http://127.0.0.1:8000/login/")
    # 12 | type | id=id_username | Brayan@gmail.com
    self.driver.find_element(By.ID, "id_username").send_keys("Brayan@gmail.com")
    # 13 | type | id=id_password | Lemu$123
    self.driver.find_element(By.ID, "id_password").send_keys("Lemu$123")
    # 14 | sendKeys | id=id_password | ${KEY_ENTER}
    self.driver.find_element(By.ID, "id_password").send_keys(Keys.ENTER)
  
