# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestChangeAddress():
  def setup_method(self, method):
    self.driver = webdriver.Chrome(executable_path='C:\Driver\chromedriver.exe')
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_changeAddress(self):
    # Test name: Change Address
    # Step # | name | target | value
    # 1 | open | http://127.0.0.1:8000/login/ | 
    self.driver.get("http://127.0.0.1:8000/login/")
    # 2 | type | id=id_username | Brayan@gmail.com
    self.driver.find_element(By.ID, "id_username").send_keys("Brayan@gmail.com")
    # 3 | type | id=id_password | Lemu$123
    self.driver.find_element(By.ID, "id_password").send_keys("Lemu$123")
    # 4 | click | css=.is-block | 
    self.driver.find_element(By.CSS_SELECTOR, ".is-block").click()
    # 5 | mouseOver | linkText=My Account | 
    element = self.driver.find_element(By.LINK_TEXT, "My Account")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    # 6 | click | linkText=My Profile | 
    self.driver.find_element(By.LINK_TEXT, "My Profile").click()
    # 7 | click | linkText=Edit Address | 
    self.driver.find_element(By.LINK_TEXT, "Edit Address").click()
    # 8 | click | id=id_state | 
    self.driver.find_element(By.ID, "id_state").click()
    # 9 | select | id=id_state | label=Alaska
    dropdown = self.driver.find_element(By.ID, "id_state")
    dropdown.find_element(By.XPATH, "//option[. = 'Alaska']").click()
    # 10 | click | css=.save | 
    self.driver.find_element(By.CSS_SELECTOR, ".save").click()
  
