# Generated by Django 4.1 on 2022-08-31 02:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="timeSlots",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tech",
                    models.EmailField(
                        max_length=254, unique=True, verbose_name="email"
                    ),
                ),
                ("_9_00_am", models.BooleanField(default=False)),
                ("_9_15am", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="weeklySchedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tech",
                    models.EmailField(
                        max_length=254, unique=True, verbose_name="email"
                    ),
                ),
                ("monday_availability", models.BooleanField(default=False)),
                ("monday_timeIn", models.TimeField()),
                ("monday_timeOut", models.TimeField()),
                ("tuesday_availability", models.BooleanField(default=False)),
                ("tuesday_time_In", models.TimeField()),
                ("tuesday_time_Out", models.TimeField()),
                (
                    "monday_timeSlots",
                    models.OneToOneField(
                        default=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mondayTimeSlots",
                        to="Scheduling.timeslots",
                    ),
                ),
            ],
        ),
    ]
