# Generated by Django 4.1 on 2022-09-29 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Scheduling", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="timeslots",
            name="arrive_time",
            field=models.TimeField(blank=True, null=True),
        ),
    ]
