# Generated by Django 4.1 on 2022-08-31 02:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Scheduling", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="weeklyschedule", name="tuesday_time_In",),
        migrations.RemoveField(model_name="weeklyschedule", name="tuesday_time_Out",),
    ]
