# Generated by Django 4.1 on 2022-08-31 04:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Scheduling", "0002_timeslots__10_00_am_timeslots__10_15am_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="timeslots", old_name="_9_00_am", new_name="nine_00_am",
        ),
    ]
