# Generated by Django 4.1 on 2022-08-31 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Scheduling", "0002_remove_weeklyschedule_tuesday_time_in_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="timeslots",
            name="dayOfWeek",
            field=models.CharField(default="monday", max_length=9),
            preserve_default=False,
        ),
    ]
