# Generated by Django 4.1 on 2022-10-05 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Scheduling", "0002_timeslots_arrive_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="technicianschedule",
            name="friday_time_In",
            field=models.TimeField(blank=True),
        ),
        migrations.AlterField(
            model_name="technicianschedule",
            name="friday_time_Out",
            field=models.TimeField(blank=True),
        ),
        migrations.AlterField(
            model_name="technicianschedule",
            name="monday_timeIn",
            field=models.TimeField(blank=True),
        ),
        migrations.AlterField(
            model_name="technicianschedule",
            name="monday_timeOut",
            field=models.TimeField(blank=True),
        ),
        migrations.AlterField(
            model_name="technicianschedule",
            name="saturday_time_In",
            field=models.TimeField(blank=True),
        ),
        migrations.AlterField(
            model_name="technicianschedule",
            name="saturday_time_Out",
            field=models.TimeField(blank=True),
        ),
        migrations.AlterField(
            model_name="technicianschedule",
            name="sunday_time_In",
            field=models.TimeField(blank=True),
        ),
        migrations.AlterField(
            model_name="technicianschedule",
            name="sunday_time_Out",
            field=models.TimeField(blank=True),
        ),
        migrations.AlterField(
            model_name="technicianschedule",
            name="thursday_time_In",
            field=models.TimeField(blank=True),
        ),
        migrations.AlterField(
            model_name="technicianschedule",
            name="thursday_time_Out",
            field=models.TimeField(blank=True),
        ),
        migrations.AlterField(
            model_name="technicianschedule",
            name="tuesday_time_In",
            field=models.TimeField(blank=True),
        ),
        migrations.AlterField(
            model_name="technicianschedule",
            name="tuesday_time_Out",
            field=models.TimeField(blank=True),
        ),
        migrations.AlterField(
            model_name="technicianschedule",
            name="wednesday_time_In",
            field=models.TimeField(blank=True),
        ),
        migrations.AlterField(
            model_name="technicianschedule",
            name="wednesday_time_Out",
            field=models.TimeField(blank=True),
        ),
    ]
