# Generated by Django 4.1 on 2022-10-08 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Scheduling", "0003_alter_technicianschedule_friday_time_in_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="technicianschedule",
            old_name="monday_timeIn",
            new_name="monday_time_In",
        ),
    ]
