# Generated by Django 4.1 on 2022-09-02 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Scheduling", "0003_rename__9_00_am_timeslots_nine_00_am"),
    ]

    operations = [
        migrations.RenameField(
            model_name="timeslots", old_name="_9_15am", new_name="nine_15am",
        ),
        migrations.RenameField(
            model_name="timeslots", old_name="_9_30am", new_name="nine_30am",
        ),
        migrations.RenameField(
            model_name="timeslots", old_name="_9_45am", new_name="nine_45am",
        ),
    ]
