# Generated by Django 4.1 on 2022-09-06 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Scheduling", "0004_rename__9_15am_timeslots_nine_15am_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="timeslots", old_name="_10_00_am", new_name="eleven_00_am",
        ),
        migrations.RenameField(
            model_name="timeslots", old_name="_10_15am", new_name="eleven_15am",
        ),
        migrations.RenameField(
            model_name="timeslots", old_name="_10_30am", new_name="eleven_30am",
        ),
        migrations.RenameField(
            model_name="timeslots", old_name="_10_45am", new_name="eleven_45am",
        ),
        migrations.RenameField(
            model_name="timeslots", old_name="_11_00_am", new_name="four_00_pm",
        ),
        migrations.RenameField(
            model_name="timeslots", old_name="_11_15am", new_name="four_15pm",
        ),
        migrations.RenameField(
            model_name="timeslots", old_name="_11_30am", new_name="four_30pm",
        ),
        migrations.RenameField(
            model_name="timeslots", old_name="_11_45am", new_name="four_45pm",
        ),
        migrations.RenameField(
            model_name="timeslots", old_name="_12_00_pm", new_name="one_00_pm",
        ),
        migrations.RenameField(
            model_name="timeslots", old_name="_12_15am", new_name="one_15pm",
        ),
        migrations.RenameField(
            model_name="timeslots", old_name="_12_30am", new_name="one_30pm",
        ),
        migrations.RenameField(
            model_name="timeslots", old_name="_12_45am", new_name="one_45pm",
        ),
        migrations.RenameField(
            model_name="timeslots", old_name="_1_00_pm", new_name="ten_00_am",
        ),
        migrations.RenameField(
            model_name="timeslots", old_name="_1_15pm", new_name="ten_15am",
        ),
        migrations.RenameField(
            model_name="timeslots", old_name="_1_30pm", new_name="ten_30am",
        ),
        migrations.RenameField(
            model_name="timeslots", old_name="_1_45pm", new_name="ten_45am",
        ),
        migrations.RenameField(
            model_name="timeslots", old_name="_2_00_pm", new_name="three_00_pm",
        ),
        migrations.RenameField(
            model_name="timeslots", old_name="_2_15pm", new_name="three_15pm",
        ),
        migrations.RenameField(
            model_name="timeslots", old_name="_2_30pm", new_name="three_30pm",
        ),
        migrations.RenameField(
            model_name="timeslots", old_name="_2_45pm", new_name="three_45pm",
        ),
        migrations.RenameField(
            model_name="timeslots", old_name="_3_00_pm", new_name="twelve_00_pm",
        ),
        migrations.RenameField(
            model_name="timeslots", old_name="_3_15pm", new_name="twelve_15am",
        ),
        migrations.RenameField(
            model_name="timeslots", old_name="_3_30pm", new_name="twelve_30am",
        ),
        migrations.RenameField(
            model_name="timeslots", old_name="_3_45pm", new_name="twelve_45am",
        ),
        migrations.RenameField(
            model_name="timeslots", old_name="_4_00_pm", new_name="two_00_pm",
        ),
        migrations.RenameField(
            model_name="timeslots", old_name="_4_15pm", new_name="two_15pm",
        ),
        migrations.RenameField(
            model_name="timeslots", old_name="_4_30pm", new_name="two_30pm",
        ),
        migrations.RenameField(
            model_name="timeslots", old_name="_4_45pm", new_name="two_45pm",
        ),
    ]
