# Generated by Django 4.1 on 2022-08-31 02:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("Scheduling", "__first__"),
        ("Account", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Technician",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bio", models.TextField(blank=True)),
                ("pay_rate", models.DecimalField(decimal_places=2, max_digits=4)),
                ("age", models.PositiveIntegerField(default=0)),
                (
                    "techSchedule",
                    models.OneToOneField(
                        default=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Scheduling.weeklyschedule",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        default=None,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
