# Generated by Django 4.1 on 2022-09-29 21:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("Scheduling", "0002_timeslots_arrive_time"),
        ("Account", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="technician",
            name="schedule",
            field=models.OneToOneField(
                blank=True,
                default=False,
                on_delete=django.db.models.deletion.CASCADE,
                to="Scheduling.technicianschedule",
            ),
        ),
    ]
