# Generated by Django 4.1 on 2022-08-30 20:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Account", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="phoneNumber",
            field=models.CharField(
                default=2222222222,
                max_length=10,
                validators=[django.core.validators.MinLengthValidator(10)],
            ),
            preserve_default=False,
        ),
    ]
