# Generated by Django 4.1 on 2022-09-30 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Account", "0002_technician_schedule"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="state",
            field=models.CharField(
                choices=[
                    ("Alabama", "Alabama"),
                    ("Alaska", "Alaska"),
                    ("Arizona", "Arizona"),
                    ("Arkansas", "Arkansas"),
                ],
                default=None,
                max_length=15,
            ),
        ),
    ]
