# Generated by Django 4.1 on 2022-08-30 23:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("Account", "0002_remove_technician_techschedule"),
    ]

    operations = [
        migrations.AddField(
            model_name="technician",
            name="techSchedule",
            field=models.OneToOneField(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="schedule",
                to="Account.schedule",
            ),
        ),
    ]
