# Generated by Django 4.1 on 2022-10-05 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Account", "0004_alter_user_state"),
    ]

    operations = [
        migrations.AddField(
            model_name="technician",
            name="profilePicture",
            field=models.ImageField(
                blank=True, default=None, null=True, upload_to="technicians/%Y/%m/%d"
            ),
        ),
    ]
