# Generated by Django 4.1 on 2022-10-06 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Account", "0005_technician_profilepicture"),
        ("Account", "0006_alter_technician_schedule_alter_user_state"),
        ("Account", "0006_alter_user_state"),
    ]

    operations = []
