# Generated by Django 4.1 on 2022-11-04 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Account", "0008_merge_20221011_1451"),
    ]

    operations = [
        migrations.AddField(
            model_name="user", name="age", field=models.IntegerField(default=0),
        ),
    ]
