# Generated by Django 4.1 on 2022-12-06 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Account", "0010_user_is_active"),
    ]

    operations = [
        migrations.CreateModel(
            name="contactCustomer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("subject", models.CharField(max_length=50)),
                ("message", models.TextField(max_length=500)),
            ],
        ),
    ]
