NailSalonProject: Appointments.models.Appointment Class Reference
Appointments.models.Appointment Class Reference
Public Member Functions
def getTotalCharge (self)
def getTotalDuration (self)
Static Public Attributes
services
customer
technician
guest_first_name = models.CharField(blank=True, null=True, max_length=25)
guest_last_name = models.CharField(blank=True, null=True, max_length=25)
totalDuration = models.IntegerField ()
totalCharge = models.FloatField (max_length=10,)
start_time = models.TimeField (blank=True, null=True)
end_time = models.TimeField (blank=True, null=True)
date = models.DateField ()
details = models.TextField (default=True, null=True)
image
tuple STATUS_OPTION
status = models.CharField (choices=STATUS_OPTION, default='active', max_length=10)
Member Function Documentation
getTotalCharge()
def Appointments.models.Appointment.getTotalCharge (self)
References Appointments.models.Appointment.totalCharge.
getTotalDuration()
def Appointments.models.Appointment.getTotalDuration (self)
References Appointments.models.Appointment.totalDuration.
Member Data Documentation
customer
Appointments.models.Appointment.customer static
Initial value:
=  models.ForeignKey ("Account.User",
                                  on_delete=models.CASCADE,
                                  default=None,
                                  null=True,
                                  blank=True)
date
Appointments.models.Appointment.date = models.DateField () static
Referenced by Scheduling.models.timeSlots.__str__().
details
Appointments.models.Appointment.details = models.TextField (default=True, null=True) static
end_time
Appointments.models.Appointment.end_time = models.TimeField (blank=True, null=True) static
guest_first_name
Appointments.models.Appointment.guest_first_name = models.CharField(blank=True, null=True, max_length=25) static
guest_last_name
Appointments.models.Appointment.guest_last_name = models.CharField(blank=True, null=True, max_length=25) static
image
Appointments.models.Appointment.image static
Initial value:
=  models.ImageField (upload_to='images/',
                               blank=True,
                               default=None,
                               null=True)
services
Appointments.models.Appointment.services static
Initial value:
=  models.ManyToManyField ("Appointments.Service",
                                       related_name='services',
                                       default=None,
                                       )
Referenced by timeslot_process._Process.assign_tech().
start_time
Appointments.models.Appointment.start_time = models.TimeField (blank=True, null=True) static
status
Appointments.models.Appointment.status = models.CharField (choices=STATUS_OPTION, default='active', max_length=10) static
STATUS_OPTION
tuple Appointments.models.Appointment.STATUS_OPTION static
Initial value:
=  (
        ('active', 'active'),
        ('inactive', 'inactive'),
    )
technician
Appointments.models.Appointment.technician static
Initial value:
=  models.ForeignKey ("Account.Technician",
                                    on_delete=models.CASCADE,
                                    default=None,
                                    null=True,
                                    blank=True)
totalCharge
Appointments.models.Appointment.totalCharge = models.FloatField (max_length=10,) static
Referenced by Appointments.models.Appointment.getTotalCharge().
totalDuration
Appointments.models.Appointment.totalDuration = models.IntegerField () static
Referenced by Appointments.models.Appointment.getTotalDuration().
The documentation for this class was generated from the following file:
C:/Users/lemus/OneDrive/Documentos/NailSalon/Appointments/models.py