NailSalonProject: Manager.views Namespace Reference
Manager.views Namespace Reference
Functions
def home (request)
def display ()
def attendance (request)
def newtech (request)
def frontend_messages (request, list mess)
def appointments_and_dates_query ()
def sale_query (list appointment_list)
def tech_query ()
def timetable ()
def attendance_techlist ()
def get_date (tmp)
Function Documentation
appointments_and_dates_query()
def Manager.views.appointments_and_dates_query ()
Referenced by Manager.views.display().
attendance()
def Manager.views.attendance (request)
attendance_techlist()
def Manager.views.attendance_techlist ()
Referenced by Manager.views.display().
display()
def Manager.views.display ()
References Manager.views.appointments_and_dates_query(), Manager.views.attendance_techlist(), Manager.views.sale_query(), Manager.views.tech_query(), and Manager.views.timetable().
Referenced by Manager.views.home().
frontend_messages()
def Manager.views.frontend_messages (request, list mess)
Referenced by Manager.views.home().
get_date()
def Manager.views.get_date (tmp)
Referenced by Manager.views.newtech().
home()
def Manager.views.home (request)
References Manager.views.display(), and Manager.views.frontend_messages().
newtech()
def Manager.views.newtech (request)
References Manager.views.get_date().
sale_query()
def Manager.views.sale_query (list appointment_list)
Referenced by Manager.views.display().
tech_query()
def Manager.views.tech_query ()
Referenced by Manager.views.display().
timetable()
def Manager.views.timetable ()
Referenced by Manager.views.display().