NailSalonProject: timeslot_process Namespace Reference
timeslot_process Namespace Reference
Classes
class _Process
class _Process_openslot
class Process
Functions
def close_timeslot (tech_email, date, list timeslots)
def get_free_tech (datetime.date sortdate, list timeslots_need, list exclusion=[])
def get_timeslot_field_bysale (starttime, duraton)
def collect_time_fieldname (starthour, startminute, duration)
def convert_time_fieldname (hour, minute)
def main ()
Variables
logger = logging.getLogger()
level
dictionary num_to_word
Function Documentation
close_timeslot()
def timeslot_process.close_timeslot (tech_email, date, list timeslots)
Referenced by timeslot_process._Process.assign_tech().
collect_time_fieldname()
def timeslot_process.collect_time_fieldname (starthour, startminute, duration)
Referenced by get_timeslot_field_bysale(), and timeslot_process.Process.open_slots().
convert_time_fieldname()
def timeslot_process.convert_time_fieldname (hour, minute)
get_free_tech()
def timeslot_process.get_free_tech (datetime.date sortdate, list timeslots_need, list exclusion = [])
References techs_queue.get_WAIT_queue().
get_timeslot_field_bysale()
def timeslot_process.get_timeslot_field_bysale (starttime, duraton)
References collect_time_fieldname().
main()
def timeslot_process.main ()
References main().
Referenced by main().
Variable Documentation
level
timeslot_process.level
logger
timeslot_process.logger = logging.getLogger()
num_to_word
dictionary timeslot_process.num_to_word
Initial value:
=  {13: 'one_', 14: 'two_', 15: 'three_', 16: 'four_',
               9: 'nine_', 10: 'ten_', 11: 'eleven_',
               12: 'twelve_', }