NailSalonProject: techs_queue Namespace Reference
techs_queue Namespace Reference
Functions
def build_fresh_wait_queue (date today_date, filedir=FILE_DIR)
def clock_tech_after_fresh_build (email)
def wait_to_work (email)
def work_to_wait (email)
def get_WAIT_queue (filedir=FILE_DIR)
def get_WORK_queue (filedir=FILE_DIR)
def save_queue (filedir=FILE_DIR)
def read_temp (filedir=FILE_DIR)
def write_temp (filedir=FILE_DIR)
tuple to_tuple (str line)
def Sort_Tuple ()
def main ()
Variables
string FILE_DIR = "helper/techs_queue"
Function Documentation
build_fresh_wait_queue()
def techs_queue.build_fresh_wait_queue (date today_date, filedir = FILE_DIR)
Referenced by cron.newday_open_job().
clock_tech_after_fresh_build()
def techs_queue.clock_tech_after_fresh_build (email)
References read_temp(), and save_queue().
get_WAIT_queue()
def techs_queue.get_WAIT_queue (filedir = FILE_DIR)
References read_temp().
Referenced by timeslot_process.get_free_tech().
get_WORK_queue()
def techs_queue.get_WORK_queue (filedir = FILE_DIR)
References read_temp().
main()
def techs_queue.main ()
read_temp()
def techs_queue.read_temp (filedir = FILE_DIR)
References to_tuple().
Referenced by clock_tech_after_fresh_build(), get_WAIT_queue(), get_WORK_queue(), wait_to_work(), and work_to_wait().
save_queue()
def techs_queue.save_queue (filedir = FILE_DIR)
References write_temp().
Referenced by clock_tech_after_fresh_build(), wait_to_work(), and work_to_wait().
Sort_Tuple()
def techs_queue.Sort_Tuple ()
to_tuple()
tuple techs_queue.to_tuple (str line)
Referenced by read_temp().
wait_to_work()
def techs_queue.wait_to_work (email)
References read_temp(), and save_queue().
Referenced by timeslot_process._Process.assign_tech().
work_to_wait()
def techs_queue.work_to_wait (email)
References read_temp(), and save_queue().
write_temp()
def techs_queue.write_temp (filedir = FILE_DIR)
Referenced by save_queue().
Variable Documentation
FILE_DIR
string techs_queue.FILE_DIR = "helper/techs_queue"