# Generated by Django 4.1 on 2022-09-29 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("Account", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="calendarEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                (
                    "technicians",
                    models.ManyToManyField(blank=True, to="Account.technician"),
                ),
            ],
        ),
    ]
