# Generated by Django 4.1 on 2022-09-23 01:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Account", "0002_remove_technician_pay_rate"),
        ("Calendar", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(old_name="calendar", new_name="calendarEntry",),
    ]
