# Generated by Django 4.1 on 2022-09-07 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Service",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=50)),
                ("description", models.TextField(max_length=150)),
                ("slug", models.SlugField()),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("duration", models.TimeField()),
                ("image", models.ImageField(upload_to="services/%Y/%m/%d")),
            ],
            options={"ordering": ("name",), "index_together": {("id", "slug")},},
        ),
<<<<<<< HEAD
    ]
=======
    ]
>>>>>>> 528aa387078ca6a132ffa581ee78b5c1a0a13164
