# Generated by Django 4.1 on 2022-09-07 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Appointments", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="service", name="duration", field=models.DurationField(),
        ),
    ]