# Generated by Django 4.1 on 2022-09-07 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Appointments", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="service", name="duration", field=models.DurationField(),
        ),
<<<<<<< HEAD
    ]
=======
<<<<<<< HEAD
    ]
=======
    ]
>>>>>>> 528aa387078ca6a132ffa581ee78b5c1a0a13164
>>>>>>> Registration
