# Generated by Django 4.1 on 2022-11-17 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Appointments", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="appointment", name="services",),
    ]
