# Generated by Django 4.1 on 2022-10-06 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Appointments", "0002_alter_sale_technician"),
        ("Appointments", "0002_appointment_technician"),
    ]

    operations = []
