# Generated by Django 4.1 on 2022-11-17 20:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("Account", "0010_user_is_active"),
        ("Appointments", "0002_remove_appointment_services"),
    ]

    operations = [
        migrations.AddField(
            model_name="appointment",
            name="services",
            field=models.ManyToManyField(
                default=None, related_name="services", to="Appointments.service"
            ),
        ),
        migrations.AlterField(
            model_name="sale",
            name="technician",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="technician",
                to="Account.technician",
            ),
        ),
    ]
