# Generated by Django 4.1 on 2022-12-07 01:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Appointments", "0003_appointment_guest_first_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appointment",
            name="end_time",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="appointment",
            name="start_time",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="sale",
            name="start_time",
            field=models.TimeField(
                blank=True, default=datetime.time(19, 40, 33, 18117), null=True
            ),
        ),
    ]
