# Generated by Django 4.1 on 2022-11-29 21:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Appointments", "0003_alter_sale_start_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sale",
            name="start_time",
            field=models.TimeField(
                blank=True, default=datetime.time(15, 25, 42, 521278), null=True
            ),
        ),
    ]
