# Generated by Django 4.1 on 2022-10-11 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Appointments', '0003_merge_20221006_1505'),
        ('Appointments', '0003_merge_20221006_1529'),
    ]

    operations = [
    ]
