# Generated by Django 4.1 on 2022-10-13 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Appointments", "0004_merge_20221011_1451"),
    ]

    operations = [
        migrations.AlterField(
            model_name="service",
            name="name",
            field=models.CharField(db_index=True, max_length=30),
        ),
        migrations.AlterField(
            model_name="service", name="slug", field=models.SlugField(max_length=30),
        ),
    ]
