# Generated by Django 4.1 on 2022-12-07 01:43

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("Account", "0011_contactcustomer"),
        ("Appointments", "0004_alter_appointment_end_time_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sale",
            name="start_time",
            field=models.TimeField(
                blank=True, default=datetime.time(19, 43, 16, 663127), null=True
            ),
        ),
        migrations.AlterField(
            model_name="sale",
            name="technician",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="technician",
                to="Account.technician",
            ),
        ),
    ]
