# Generated by Django 4.1 on 2022-11-21 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Appointments', '0004_alter_appointment_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='start_time',
            field=models.TimeField(default=None),
        ),
    ]
