# Generated by Django 4.1 on 2022-12-07 01:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Appointments", "0005_alter_sale_start_time_alter_sale_technician"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sale",
            name="start_time",
            field=models.TimeField(
                blank=True, default=datetime.time(19, 43, 21, 323078), null=True
            ),
        ),
    ]
