# Generated by Django 4.1 on 2022-10-26 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Appointments", "0005_alter_service_name_alter_service_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="appointment",
            name="details",
            field=models.TextField(blank=True, null=True),
        ),
    ]
