# Generated by Django 4.1 on 2022-09-07 21:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("Appointments", "0005_alter_service_duration_appointment"),
    ]

    operations = [
        migrations.AddField(
            model_name="appointment",
            name="customer",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
<<<<<<< HEAD
    ]
=======
    ]
>>>>>>> 528aa387078ca6a132ffa581ee78b5c1a0a13164
