# Generated by Django 4.1 on 2022-11-25 23:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Appointments', '0004_alter_appointment_technician'),
        ('Appointments', '0005_sale_start_time'),
    ]

    operations = [
    ]
