# Generated by Django 4.1 on 2022-09-07 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Appointments", "0006_appointment_customer"),
    ]

    operations = [
        migrations.RemoveField(model_name="appointment", name="services",),
        migrations.AddField(
            model_name="appointment",
            name="services",
            field=models.ManyToManyField(
                default=None,
                null=True,
                related_name="services",
                to="Appointments.service",
            ),
        ),
    ]
