# Generated by Django 4.1 on 2022-12-07 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Appointments', '0003_alter_sale_start_time'),
        ('Appointments', '0006_alter_sale_start_time'),
    ]

    operations = [
    ]
