# Generated by Django 4.1 on 2022-10-26 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Appointments", "0006_appointment_details"),
    ]

    operations = [
        migrations.AddField(
            model_name="appointment",
            name="completed",
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
