# Generated by Django 4.1 on 2022-11-25 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Appointments', '0006_merge_20221125_1713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='start_time',
            field=models.TimeField(blank=True, default=None, null=True),
        ),
    ]
