# Generated by Django 4.1 on 2022-10-26 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Appointments", "0007_appointment_completed"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appointment",
            name="completed",
            field=models.BooleanField(default=False, null=True),
        ),
    ]
