# Generated by Django 4.1 on 2022-12-07 06:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Appointments', '0007_merge_20221206_2324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='start_time',
            field=models.TimeField(blank=True, default=datetime.time(0, 59, 49, 454764), null=True),
        ),
    ]
