# Generated by Django 4.1 on 2023-01-29 18:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Appointments", "0008_alter_sale_start_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sale",
            name="start_time",
            field=models.TimeField(
                blank=True, default=datetime.time(12, 7, 2, 341371), null=True
            ),
        ),
    ]
