# Generated by Django 4.1 on 2022-11-14 22:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0010_user_is_active'),
        ('Appointments', '0009_remove_appointment_completed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='technician',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='technician', to='Account.technician'),
        ),
    ]
