# Generated by Django 4.1 on 2022-11-15 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Appointments", "0009_remove_appointment_completed_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="appointment",
            name="status",
            field=models.CharField(
                choices=[
                    ("scheduled", "scheduled"),
                    ("working", "working"),
                    ("closed", "closed"),
                    ("canceled", "canceled"),
                ],
                default="scheduled",
                max_length=10,
            ),
        ),
    ]
