# Generated by Django 4.1 on 2022-09-08 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Appointments", "0009_appointment_date_appointment_end_time_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=200)),
                ("slug", models.SlugField(max_length=200, unique=True)),
            ],
            options={
                "verbose_name": "category",
                "verbose_name_plural": "categories",
                "ordering": ("name",),
            },
        ),
<<<<<<< HEAD
    ]
=======
<<<<<<< HEAD
    ]
=======
    ]
>>>>>>> 528aa387078ca6a132ffa581ee78b5c1a0a13164
>>>>>>> Registration
