# Generated by Django 4.1 on 2022-11-16 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Appointments", "0010_appointment_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="sale", name="quantity", field=models.IntegerField(default=1),
        ),
    ]
