# Generated by Django 4.1 on 2022-09-08 19:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("Appointments", "0010_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="category",
            field=models.ForeignKey(
                blank=True,
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="products",
                to="Appointments.category",
            ),
        ),
    ]
