# Generated by Django 4.1 on 2022-11-15 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Appointments', '0010_alter_sale_technician'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
