# Generated by Django 4.1 on 2022-11-16 01:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Appointments", "0011_sale_quantity"),
    ]

    operations = [
        migrations.RemoveField(model_name="appointment", name="services",),
    ]
