# Generated by Django 4.1 on 2022-11-16 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Appointments', '0011_alter_service_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='details',
            field=models.TextField(default=True, null=True),
        ),
    ]
