# Generated by Django 4.1 on 2022-11-17 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Appointments", "0013_remove_sale_quantity"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appointment",
            name="totalCharge",
            field=models.FloatField(max_length=10),
        ),
    ]
